version: '3'

networks:
  Vehicle-Plus-Network:
    ipam:
      config:
        - subnet: 163.20.0.0/16
  databasesys_Database-Network:
    external: true

services:
  auth-server-service:
    image: registry.digitalocean.com/vehicle-plus/auth-server:latest
    restart: always
    command: bash -c "dotnet AuthenticationServer.dll"
    volumes:
      - ./AuthServer/certificate.crt:/certificates/certificate.crt
      - ./AuthServer/private_key.pem:/certificates/private_key.pem
      - ./AuthServer/public_key.pem:/certificates/public_key.pem
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 127.0.0.1:5440:80
    networks:
      Vehicle-Plus-Network:
        ipv4_address: 163.20.0.15
      databasesys_Database-Network:
        ipv4_address: 163.50.0.15
  alerts-service:
    image: registry.digitalocean.com/vehicle-plus/alerts:latest
    restart: always
    command: bash -c "sleep 10 && dotnet Alert-Server.dll"
    volumes:
      - ./fcm/vehicleplus-notifications.json:/fcm/vehicleplus-notifications.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 127.0.0.1:5460:80
    depends_on:
      - mqtt-broker
    networks:
      Vehicle-Plus-Network:
        ipv4_address: 163.20.0.25
      databasesys_Database-Network:
        ipv4_address: 163.50.0.25
  mqtt-broker:
    image: emqx/emqx:5.0.26
    restart: always
    ports:
      - 1883:1883 
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 127.0.0.1:18083:18083
    networks:
      Vehicle-Plus-Network:
        ipv4_address: 163.20.0.20
      databasesys_Database-Network:
        ipv4_address: 163.50.0.20