version: '3'

networks:
  Vehicle-Plus-Network:
    ipam:
      config:
        - subnet: 163.20.0.0/16

services:
  auth-server-service:
    image: registry.digitalocean.com/vehicle-plus/auth-server:latest
    restart: always
    command: bash -c "dotnet AuthenticationServer.dll"
    volumes:
      - ./AuthServer/certificate.crt:/certificates/certificate.crt
      - ./AuthServer/private_key.pem:/certificates/private_key.pem
      - ./AuthServer/public_key.pem:/certificates/public_key.pem
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 127.0.0.1:5440:80
    networks:
      Vehicle-Plus-Network:
        ipv4_address: 163.20.0.15
  alerts-service:
    image: registry.digitalocean.com/vehicle-plus/alerts:latest
    restart: always
    command: bash -c "dotnet Alert-Server.dll"
    volumes:
      - ./fcm/vehicleplus-notifications.json:/fcm/vehicleplus-notifications.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 127.0.0.1:5460:80
    networks:
      Vehicle-Plus-Network:
        ipv4_address: 163.20.0.25
  gps-service:
    image: registry.digitalocean.com/vehicle-plus/gps-server:latest
    restart: always
    command: bash -c "dotnet GPS-Server.dll"
    volumes:
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 127.0.0.1:5480:80
    networks:
      Vehicle-Plus-Network:
        ipv4_address: 163.20.0.30
